Update parse-iommu-devices

diff --git a/bin/parse-iommu-devices b/bin/parse-iommu-devices
--- a/bin/parse-iommu-devices
+++ b/bin/parse-iommu-devices
@@ -10,6 +10,13 @@
 # Version:        1.0.2
 #
 
+#
+# TODO:
+# - [ ] add validation for all inputs.
+# - [ ] fix output to show every IOMMU group and it's device info.
+# - [ ] fix lists?
+#
+
 shopt -s nullglob
 
 declare -r SCRIPT_VERSION="1.0.2"
@@ -43,8 +50,10 @@ declare -A OUTPUTS=(
 
 function append_output_to_lists
 {
-  if ! is_quiet_enabled \
-    && ! is_output_empty; then
+  # if ! is_quiet_enabled \
+  #   && ! is_output_empty; then
+
+  if ! is_quiet_enabled; then
     group_output=(
       "IOMMU Group ${group_id}:"
       "${group_output[@]}"
@@ -78,18 +87,20 @@ function append_output_to_lists
 function append_output_to_temp_lists
 {
   if ! is_quiet_enabled; then
+    local driver_output="\t\tDriver:\t\t"
+
+    if [[ ! -z "${driver}" ]]; then
+      driver_output+="${driver}"
+    else
+      driver_output+="N/A"
+    fi
+
     group_output+=(
       "\t${index}.\tSlot ID:\t\t${bus_id}"
       "\t\tName:\t\t${name}"
       "\t\tHardware ID:\t${hardware_id}"
-      "\t\tDriver:\t\t"
+      "${driver_output}"
     )
-
-    if [[ ! -z "${driver}" ]]; then
-      group_output[-1]+="${driver}"
-    else
-      group_output[-1]+="N/A"
-    fi
 
     group_output+=( "" )
   fi
@@ -261,6 +272,28 @@ function convert_selected_hardware_id_list_to_delimited_string
   )"
 }
 
+function convert_unselected_group_id_list_to_delimited_string
+{
+  if [[ -z "${OUTPUTS["UNSELECTED_GROUP_ID_LIST"]}" ]]; then
+    OUTPUTS["UNSELECTED_GROUP_ID_LIST"]="N/A"
+    return 0
+  fi
+
+  OUTPUTS["UNSELECTED_GROUP_ID_LIST"]="${OUTPUTS["UNSELECTED_GROUP_ID_LIST"]::-1}"
+
+  OUTPUTS["UNSELECTED_GROUP_ID_LIST"]="$( \
+    echo "${OUTPUTS["UNSELECTED_GROUP_ID_LIST"]}" \
+      | sed --expression $'s/,/\\\n/g' \
+      | sort --numeric-sort \
+      | tr '\n' ',' \
+      | sed 's/.$//' \
+      | tr ',' '\n' \
+      | sort --human-numeric-sort --unique \
+      | xargs \
+      | tr ' ' ','
+  )"
+}
+
 function is_quiet_enabled
 {
   if ! "${ARGUMENTS["GET_MINIMUM_OUTPUT"]}"; then
@@ -294,6 +327,10 @@ function print_output
     return 1
   fi
 
+  for line in ${group_output{@}}; do
+    echo -e "${line}"
+  done
+
   echo -e "Groups:\n${OUTPUTS["FOUND_GROUP_ID_LIST"]}"
   echo
   echo -e "Groups with Host device(s):\n${OUTPUTS["FOUND_HOST_GROUP_ID_LIST"]}"
@@ -301,6 +338,8 @@ function print_output
   echo -e "Groups with PCI device(s):\n${OUTPUTS["FOUND_PCI_GROUP_ID_LIST"]}"
   echo
   echo -e "Groups with VGA device(s):\n${OUTPUTS["FOUND_VGA_GROUP_ID_LIST"]}"
+  echo
+  echo -e "Unselected Groups:\n${OUTPUTS["UNSELECTED_GROUP_ID_LIST"]}"
   echo
   echo -e "Selected Groups:\n${OUTPUTS["SELECTED_GROUP_ID_LIST"]}"
   echo
@@ -407,30 +446,9 @@ function parse_argument
   done
 }
 
-function parse_invalid_option
-{
-  if [[ "${1}" != "-"* ]] \
-    && [[ ! -z "${1}" ]]; then
-    return 0
-  fi
-
-  is_quiet_enabled && exit 1
-  echo -e "Error: Invalid option specified."
-  exit 1
-}
-
-function print_invalid_argument
-{
-  echo -e "Error: Invalid option specified."
-  echo -e "Error: Invalid argument(s) specified."
-  print_usage
-  exit 1
-}
-
-function print_groups
+function parse_groups
 {
   vga_group_index=0
-  declare -a group_output=()
 
   for group in $( \
     find /sys/kernel/iommu_groups/* -maxdepth 0 -type d \
@@ -465,16 +483,32 @@ function print_groups
       set_reverse_name_match_property
       set_vga_type_match_property
 
+      if "${ARGUMENTS["MATCH_HOST"]}" \
+          && ! "${has_host}" \
+          && ! "${ARGUMENTS["MATCH_PCI"]}"; then
+        continue
+      fi
+
       if "${ARGUMENTS["MATCH_PCI"]}" \
           && ! "${has_pci}" \
-          && ! "${ARGUMENTS["MATCH_HOST"]}" \
-        || "${ARGUMENTS["MATCH_HOST"]}" \
-          && ! "${has_host}" \
-          && ! "${ARGUMENTS["MATCH_PCI"]}" \
-        "${ARGUMENTS["MATCH_NAMES"]}" \
+          && ! "${ARGUMENTS["MATCH_HOST"]}"; then
+        continue
+      fi
+
+      if "${ARGUMENTS["MATCH_NAMES"]}" \
           && ! "${has_name}" \
-        "${ARGUMENTS["REVERSE_MATCH_NAMES"]}" \
-          && ! "${has_reverse_name}"; then
+          && ! "${ARGUMENTS["REVERSE_MATCH_NAMES"]}"; then
+        continue
+      fi
+
+      if "${ARGUMENTS["REVERSE_MATCH_NAMES"]}" \
+          && ! "${has_reverse_name}" \
+          && ! "${ARGUMENTS["MATCH_NAMES"]}"; then
+        continue
+      fi
+
+      if "${ARGUMENTS["MATCH_VGA_GROUP_INDEX"]}" \
+          && ! "${has_vga}"; then
         continue
       fi
 
@@ -493,6 +527,27 @@ function print_groups
   convert_selected_driver_list_to_delimited_string
   convert_selected_group_id_list_to_delimited_string
   convert_selected_hardware_id_list_to_delimited_string
+  convert_unselected_group_id_list_to_delimited_string
+}
+
+function parse_invalid_option
+{
+  if [[ "${1}" != "-"* ]] \
+    && [[ ! -z "${1}" ]]; then
+    return 0
+  fi
+
+  is_quiet_enabled && exit 1
+  echo -e "Error: Invalid option specified."
+  exit 1
+}
+
+function print_invalid_argument
+{
+  echo -e "Error: Invalid option specified."
+  echo -e "Error: Invalid argument(s) specified."
+  print_usage
+  exit 1
 }
 
 function print_usage
@@ -630,6 +685,33 @@ function set_vga_type_match_property
   fi
 }
 
+function verify_groups
+{
+  local -i greatest_iommu="$( \
+    ls /sys/kernel/iommu_groups/ \
+      | sort --reverse --version-sort \
+      | head --lines 1
+  )"
+
+  local -i min_iommu=0
+
+  if $( \
+      echo "${ARGUMENTS["GROUPS_TO_MATCH"]}" \
+      | grep --extended-regexp --quiet '^(?!\d+(,\d+)*$)([^,]+(,[^,]+)*)?$'
+    ) \
+    || [[ "$( \
+      echo "${ARGUMENTS["GROUPS_TO_MATCH"]}" \
+      | sort --reverse --version-sort
+      | --lines 1
+    )" -gt "${greatest_iommu}" ]]; then
+    echo -e "Error: Invalid IOMMU group ID(s) specified."
+
+    echo "Please enter a number between '${min_iommu}' and '${greatest_iommu}'."
+
+    exit 1
+  fi
+}
+
 function verify_vga_group_index
 {
   vga_group_index="${1}"
@@ -648,6 +730,7 @@ function verify_vga_group_index
 
     is_quiet_enabled && exit 1
     echo -e "Error: Invalid index specified."
+
     echo "Please enter a value between '${MIN_VGA_INDEX_VALUE}' and" \
       "'${vga_group_index}'."
 
@@ -658,7 +741,15 @@ function verify_vga_group_index
 function main
 {
   parse_arguments "${@}"
-  print_groups
+
+  declare -a group_output=()
+
+  if is_quiet_enabled; then
+    parse_groups &> /dev/null
+  else
+    parse_groups
+  fi
+
   print_output
 }
 
